project:
  type: website
  output-dir: docs

website:
  title: "Dissertation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - me.qmd
      - projects.qmd
      - books.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

